library(rPython)
python.load("data_combination.py")
counts <- read.delim(combined_data,"\t")
library("scde")
models <- scde.error.models(counts)
prior <- scde.expression.prior(models, counts)
scde.expression.difference(models, counts,prior)